### ISSUE TITLE
10/11 todo

### ISSUE THREAD

**Issue by 1Consumption** [1Consumption/IDIllust#3]
## 모카
- [ ] 카테고리 순서 변경(skin - eye - eyebrow - nose - mouth - hair - clothes - accessory - background 순으로 변경)
- [ ] component 클릭시 미리보기 이미지 내려주기
- [ ] 앱에서 보낸 component id들에 맞는 원본 이미지 내려주기

## 올라프
- [ ] customizeView 완성하기

## T암
- [ ] 카테고리 이미지 테두리 따기
- [ ] 배경색 RGB값 주기
